apiVersion: v1
kind: Service
metadata:
  labels:
    app: sms-gateway-server
    name: sms-gateway-server
spec:
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
  selector:
    app: sms-gateway-server
    tier: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-gateway-server
  labels:
    app: sms-gateway-server
spec:
  selector:
    matchLabels:
      app: sms-gateway-server
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sms-gateway-server
        tier: backend
    spec:
      containers:
        - name: sms-gateway-server
          image: muellners/finscale-sms-service:latest
          env:
            - name: DRIVERCLASS_NAME
              value: org.drizzle.jdbc.DrizzleDriver
            - name: PROTOCOL
              value: jdbc
            - name: SUB_PROTOCOL
              value: mysql:thin
            - name: fineract_tenants_driver
              value: org.drizzle.jdbc.DrizzleDriver
            - name: fineract_tenants_url
              value: jdbc:mysql:thin://fineractmysql:3306/fineract_tenants
            - name: fineract_tenants_uid
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants-db-secret
                  key: username
            - name: fineract_tenants_pwd
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants-db-secret
                  key: password
            - name: FINERACT_DEFAULT_TENANTDB_HOSTNAME
              value: fineractmysql
            - name: FINERACT_DEFAULT_TENANTDB_PORT
              value: '3306'
            - name: FINERACT_DEFAULT_TENANTDB_UID
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants-db-secret
                  key: username
            - name: FINERACT_DEFAULT_TENANTDB_PWD
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants-db-secret
                  key: password
          ports:
            - containerPort: 8443
              name: fineract-server
